name: iOS CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run on push to main branch

jobs:
  build:
    runs-on: macos-latest  # Required for iOS builds

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Ruby (for Cocoapods if needed)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies via Cocoapods
        run: |
          cd ios
          pod install
        if: exists('ios/Podfile')

      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app  # Adjust version as needed

      - name: Build the iOS app
        run: |
          xcodebuild -workspace YourApp.xcworkspace \
                     -scheme YourApp \
                     -sdk iphoneos \
                     -configuration Release \
                     clean build

      # Optional: Export .ipa file
      - name: Archive and export IPA
        run: |
          xcodebuild -workspace YourApp.xcworkspace \
                     -scheme YourApp \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $PWD/build/YourApp.xcarchive archive

          xcodebuild -exportArchive \
                     -archivePath $PWD/build/YourApp.xcarchive \
                     -exportOptionsPlist ios/ExportOptions.plist \
                     -exportPath $PWD/build

      # Optional: Upload artifact
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v3
        with:
          name: iOS-App
          path: build/*.ipa
